name: isacs_mobile
description: Integrated Semi Automatic Chopper System
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  another_flushbar: ^1.12.30
  auto_route: ^10.1.0+1
  bloc: ^8.1.4
  cloud_firestore: ^6.0.0
  dartz: ^0.10.1
  dio: ^5.8.0+1
  easy_debounce: ^2.0.3
  expandable: ^5.0.1
  firebase_core: ^4.0.0
  firebase_database: ^12.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_gemini: ^3.0.0
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  iconsax_plus: ^1.0.0
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  loader_overlay: ^5.0.0
  logger: ^2.6.0
  material_symbols_icons: ^4.2858.1
  percent_indicator: ^4.2.5
  shared_preferences: ^2.5.3
  sizer: ^3.0.5
  skeletonizer: ^1.4.3
  syncfusion_flutter_charts: ^29.1.38
  url_launcher: ^6.3.2

dev_dependencies:
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/onboarding/
    - .env
