// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCRhmj7vKf4OJkGmV-3RHVyjNVpIetQc8',
    appId: '1:804023191711:android:150f893b82c1a65c9abaaa',
    messagingSenderId: '804023191711',
    projectId: 'interstellar-iot',
    databaseURL: 'https://interstellar-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'interstellar-iot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNQvk9BSk4pNriBq4H5Tmi_GzE-6tA-mw',
    appId: '1:804023191711:ios:d9d8a2b158a6d0f99abaaa',
    messagingSenderId: '804023191711',
    projectId: 'interstellar-iot',
    databaseURL: 'https://interstellar-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'interstellar-iot.firebasestorage.app',
    iosBundleId: 'com.interstellar.isacs',
  );
}
